input_parquet = "generated_data/TPCDS_100/synthetic_data/output.parquet"
destination_folder = "generated_data/TPCDS_100/filtered_queries/"
empty_set  = true
stratified_sampling = true 

[stratified_sampling_config]
queries_per_bin = 100
upper_bound = 1000000
total_bins = 10000
