input_parquet = "generated_data/TPCDS_100/synthetic_data/output.parquet"
destination_folder = "generated_data/TPCDS_100/filtered_queries/"
filter_null  = true
cherry_pick = true 

[cherry_pick_config]
queries_per_bin = 100
upper_bound = 1000000
total_bins = 10000
