destination_folder = "generated_data/TPCDS_100/transformed_queries/"
max_output_size = 100
timeout_seconds = 15
queries_folder = "generated_data/TPCDS_100/extended_queries_ollama/"
duckdb_database = "generated_data/TPCDS_100/database/TPCDS_100.duckdb"
