input_parquet = "tmp/transformed_queries_ollama/traces_duckdb.parquet"
output_folder = "tmp/metrics_ollama/"
[template_occurrence_limit]
union = 2

[x_axis_limits]
cumulative_cardinality_duckdb = [1, 5e6]
