llm_extension = true
union_extension = true
queries_parquet = "tmp/filtered_queries/filtered.parquet"
destination_folder = "tmp/extended_queries_ollama"
ollama_model = "llama3:latest"

[union_params]
max_queries = 5
probability = 0.7

[llm_params]
database_path = "tmp/database_TPCDS_0.1.duckdb"
retry = 0
total_queries = 7
prompts_path = "params_config/prompts/basic_prompt.toml"
schema_path = "params_config/schemas/dev.txt"
