llm_extension = true
union_extension = true
destination_folder = "generated_data/TPCDS_100/extended_queries_ollama/"
queries_parquet = "generated_data/TPCDS_100/filtered_queries/filtered.parquet"
ollama_model = "llama4:16x17b"

[union_params]
max_queries = 5
probability = 0.7


[llm_params]
database_path = "generated_data/TPCDS_100/database_test/TPCDS_0.1.duckdb"
retry = 1
total_queries = 10000
prompts_path = "params_config/prompts/standard_prompt.toml"
schema_path = "params_config/schemas/tpcds.txt"
