llm_extension = true
union_extension = true
destination_folder = "generated_data/TPCH/extended_queries_ollama/"
queries_parquet = "generated_data/TPCH/filtered_queries/filtered.parquet"
ollama_model = "llama3:latest"

[union_params]
max_queries = 5
probability = 0.7


[llm_params]
database_path = "generated_data/TPCH/database/TPCH_0.1.duckdb"
retry = 1
total_queries = 5
prompts_path = "params_config/prompts/basic_prompt.toml"
schema_path = "params_config/schemas/dev.txt"
